### ISSUE TITLE
java.lang.IllegalStateException: Not connected Exception on unsubscribe

### ISSUE THREAD

**Issue by nishant-kumar12** [datasift/datasift-java#63]
java.lang.IllegalStateException: Not connected
        at io.higgs.ws.client.WebSocketStream.emit(WebSocketStream.java:48)
        at com.datasift.client.stream.StreamingData.unsubscribe(StreamingData.java:198)
      
while executing datasiftClient.liveStream().unsubscribe(currentStream);

**Comment by zcourts** [comment]
Fixed by https://github.com/datasift/datasift-java/commit/fa9ea11e1bb7d1d6c9f066727ca195268c1af4c0
