### ISSUE TITLE
Intermittent API errors breaking Pull

### ISSUE THREAD

**Issue by paulmozo** [datasift/datasift-java#64]
While using pull the user can experience API errors resulting in an exception, these need to be handled more gracefully.

Stack trace:

```
2014-07-02 14:26:02 i.n.c.DefaultChannelPipeline [WARN] An exception was 
thrown by a user handler's exceptionCaught() method while handling the 
following exception: 
com.datasift.client.exceptions.DataSiftException: Unknown error 
at 
com.datasift.client.DataSiftApiClient$1.apply(DataSiftApiClient.java:60) 
~[stormjar.jar:na] 
at 
com.datasift.client.DataSiftApiClient$1.apply(DataSiftApiClient.java:37) 
~[stormjar.jar:na] 
at io.higgs.http.client.readers.PageReader.done(PageReader.java:24) 
~[stormjar.jar:na] 
at io.higgs.http.client.readers.Reader.setCompleted(Reader.java:77) 
~[stormjar.jar:na] 
at io.higgs.http.client.Response.setCompleted(Response.java:72) 
~[stormjar.jar:na] 
at 
io.higgs.http.client.ClientHandler.channelRead0(ClientHandler.java:57) 
~[stormjar.jar:na] 
at 
io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:103) 
~[stormjar.jar:na] 
at 
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332) 
[stormjar.jar:na] 
at 
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318) 
[stormjar.jar:na] 
at 
io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) 
[stormjar.jar:na] 
at 
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332) 
[stormjar.jar:na] 
at 
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318) 
[stormjar.jar:na] 
at 
io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) 
[stormjar.jar:na] 
at 
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332) 
[stormjar.jar:na] 
at 
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318) 
[stormjar.jar:na] 
at 
io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) 
[stormjar.jar:na] 
at 
io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:148) 
[stormjar.jar:na] 
at 
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332) 
[stormjar.jar:na] 
at 
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318) 
[stormjar.jar:na] 
at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:990) 
[stormjar.jar:na] 
at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:873) 
[stormjar.jar:na] 
at 
io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:241) 
[stormjar.jar:na] 
at 
io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) 
[stormjar.jar:na] 
at 
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332) 
[stormjar.jar:na] 
at 
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318) 
[stormjar.jar:na] 
at 
io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) 
[stormjar.jar:na] 
at 
io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125) 
[stormjar.jar:na] 
at 
io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:507) 
[stormjar.jar:na] 
at 
io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:464) 
[stormjar.jar:na] 
at 
io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:378) 
[stormjar.jar:na] 
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:350) 
[stormjar.jar:na] 
at 
io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) 
[stormjar.jar:na] 
at java.lang.Thread.run(Thread.java:745) [na:1.7.0_55]
```

**Comment by dugjason** [comment]
Issue was caused by API; not client library
