### ISSUE TITLE
Exception in operationComplete()

### ISSUE THREAD

**Issue by paulmozo** [datasift/datasift-java#65]
This was received while using the Java client, any idea what could have caused it?

io.netty.util.internal.logging.Slf4JLogger 10:04:46,769 WARN DefaultPromise:151 - An exception was thrown by io.higgs.http.client.Request$1.operationComplete() 
io.netty.util.concurrent.BlockingOperationException: DefaultChannelPromise@65ef3cb0(incomplete) 
at io.netty.util.concurrent.DefaultPromise.checkDeadLock(DefaultPromise.java:397) 
at io.netty.channel.DefaultChannelPromise.checkDeadLock(DefaultChannelPromise.java:157) 
at io.netty.util.concurrent.DefaultPromise.awaitUninterruptibly(DefaultPromise.java:290) 
at io.netty.channel.DefaultChannelPromise.awaitUninterruptibly(DefaultChannelPromise.java:135) 
at io.netty.channel.DefaultChannelPromise.awaitUninterruptibly(DefaultChannelPromise.java:28) 
at io.higgs.http.client.POST.doRequest(POST.java:71) 
at io.higgs.http.client.POST.makeTheRequest(POST.java:66) 
at io.higgs.http.client.Request$1.operationComplete(Request.java:165) 
at io.higgs.http.client.Request$1.operationComplete(Request.java:161) 
at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:682) 
at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:607) 
at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:565) 
at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:413) 
at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:82) 
at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:254) 
at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:288) 
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:524) 
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:464) 
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:378) 
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:350) 
at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) 
at java.lang.Thread.run(Thread.java:744) 
io.netty.util.internal.logging.Slf4JLogger 10:04:48,913 WARN DefaultPromise:151 - An exception was thrown by io.higgs.http.client.Request$1.operationComplete() 
io.netty.util.concurrent.BlockingOperationException: DefaultChannelPromise@6c5330ab(incomplete) 
at io.netty.util.concurrent.DefaultPromise.checkDeadLock(DefaultPromise.java:397) 
at io.netty.channel.DefaultChannelPromise.checkDeadLock(DefaultChannelPromise.java:157) 
at io.netty.util.concurrent.DefaultPromise.awaitUninterruptibly(DefaultPromise.java:290) 
at io.netty.channel.DefaultChannelPromise.awaitUninterruptibly(DefaultChannelPromise.java:135) 
at io.netty.channel.DefaultChannelPromise.awaitUninterruptibly(DefaultChannelPromise.java:28) 
at io.higgs.http.client.POST.doRequest(POST.java:71) 
at io.higgs.http.client.POST.makeTheRequest(POST.java:66) 
at io.higgs.http.client.Request$1.operationComplete(Request.java:165) 
at io.higgs.http.client.Request$1.operationComplete(Request.java:161) 
at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:682) 
at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:607) 
at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:565) 
at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:413) 
at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:82) 
at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:254) 
at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:288) 
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:524) 
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:464) 
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:378) 
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:350) 
at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) 
at java.lang.Thread.run(Thread.java:744)

**Comment by dugjason** [comment]
Issue was caused by user's code blocking client threads

**Comment by brew42** [comment]
Hi
Have you any more details on why you received the warnings above. We upgraded our datasift client jars to 'com.datasift.client:datasift-java:3.2.3' and started seeing these warnings when creating a rule on datasift. We haven't changed any of the calling code.

Tom

Ps We had some issues with netty-common and nettty-all jars also so we forced the omission of netty-common in our build.gradle

compile('com.datasift.client:datasift-java:3.2.3') {
		exclude module: 'netty-common'
		}

**Comment by brew42** [comment]
Hi zCourts

What action should we take to resolve on our build?

Tom

**Comment by zcourts** [comment]
Hi @brew42,
Updating your pom to version 3.2.4 should be all that's required.
It has been released to maven central but can take 1-2hrs to show up. When it does it'll be at http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22datasift-java%22

**Comment by brew42** [comment]
Thanks,ill try that tomorrow and confirm if ok.
