### ISSUE TITLE
Netty Issue with datasift client for steaming api

### ISSUE THREAD

**Issue by narxgun** [datasift/datasift-java#72]
We are using the datasift client (3.1.0 jar) streaming api and I see the CPU usage going up 100% after few hours and the application hangs. The datasift client thread is in runnable state and the thread dump is very similar to the netty epoll issue mentioned here - https://github.com/netty/netty/issues/327

This happens very frequently and I'll provide the exact thread dump if this happens again (the original dump was deleted by accident).

**Comment by narxgun** [comment]
This issue doesn't happen very often and we haven't seen this issue in the last month. 
~8 interactions per second.

**Comment by nishant-kumar12** [comment]
I am getting this issue everytime <version>3.2.4</version>

2015-02-26 08:45:27 i.n.u.c.DefaultPromise [WARN] An exception was thrown by io.higgs.http.client.Request$1.operationComplete()
io.netty.util.concurrent.BlockingOperationException: DefaultChannelPromise@1837ec59(incomplete)
        at io.netty.util.concurrent.DefaultPromise.checkDeadLock(DefaultPromise.java:390) [stormjar.jar:na]
        at io.netty.channel.DefaultChannelPromise.checkDeadLock(DefaultChannelPromise.java:157) [stormjar.jar:na]
        at io.netty.util.concurrent.DefaultPromise.awaitUninterruptibly(DefaultPromise.java:283) [stormjar.jar:na]
        at io.netty.channel.DefaultChannelPromise.awaitUninterruptibly(DefaultChannelPromise.java:135) [stormjar.jar:na]
        at io.netty.channel.DefaultChannelPromise.awaitUninterruptibly(DefaultChannelPromise.java:28) [stormjar.jar:na]
        at io.higgs.http.client.POST.doRequest(POST.java:54) ~[stormjar.jar:na]
        at io.higgs.http.client.POST.makeTheRequest(POST.java:49) ~[stormjar.jar:na]
        at io.higgs.http.client.Request$1.operationComplete(Request.java:197) ~[stormjar.jar:na]
        at io.higgs.http.client.Request$1.operationComplete(Request.java:193) ~[stormjar.jar:na]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:680) [stormjar.jar:na]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:603) [stormjar.jar:na]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:563) [stormjar.jar:na]
        at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:406) [stormjar.jar:na]
        at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:82) [stormjar.jar:na]
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:253) [stormjar.jar:na]
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:288) [stormjar.jar:na]
        at io.netty.channel.nio.NioEventLoopt io.netty.util.concurrent.DefaultPromise.awaitUninterruptibly.processSelectedKey(NioEventLoop.java:528) [stormjar.jar:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [stormjar.jar:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [stormjar.jar:na]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [stormjar.jar:na]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [stormjar.jar:na]
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [stormjar.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_71]
